[debug] ----------------------------------------------------------------------
[debug] Command:      /Users/bperlik/.nvm/versions/node/v6.7.0/bin/node /Users/bperlik/.nvm/versions/node/v6.7.0/bin/firebase serve
[debug] CLI Version:  3.2.1
[debug] Platform:     darwin
[debug] Node Version: v6.7.0
[debug] Time:         Thu Jan 19 2017 16:53:15 GMT-0500 (EST)
[debug] ----------------------------------------------------------------------
[debug] 
[info] Starting Firebase development server...
[info] 
[info] Project Directory: /Users/bperlik/bloc/bloc-chat
[debug] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/Users/bperlik/.nvm/versions/node/v6.7.0/lib/node_modules/firebase-tools/commands/serve.js:26:15)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1278:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[error] 
[error] Error: An unexpected error has occurred.
[debug] ----------------------------------------------------------------------
[debug] Command:      /Users/bperlik/.nvm/versions/node/v6.7.0/bin/node /Users/bperlik/.nvm/versions/node/v6.7.0/bin/firebase serve
[debug] CLI Version:  3.2.1
[debug] Platform:     darwin
[debug] Node Version: v6.7.0
[debug] Time:         Thu Jan 19 2017 16:53:25 GMT-0500 (EST)
[debug] ----------------------------------------------------------------------
[debug] 
[info] Starting Firebase development server...
[info] 
[info] Project Directory: /Users/bperlik/bloc/bloc-chat
[debug] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/Users/bperlik/.nvm/versions/node/v6.7.0/lib/node_modules/firebase-tools/commands/serve.js:26:15)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1278:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[error] 
[error] Error: An unexpected error has occurred.
